Final_Project_PRN221/Pages/Admin/ElectricBill.cshtml.cs
using Final_Project_PRN221.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Final_Project_PRN221.Pages.Admin
{
    public class ElectricBillModel : PageModel
    {
        private readonly Project_PRN221Context _context;
        public ElectricBillModel(Project_PRN221Context context)
        {
            _context = context;
        }
        public DateTime fromDate = new DateTime();
        public DateTime toDate = new DateTime();
        public decimal total { get; set; }
        public string RoomName { get; set; }
        [BindProperty]
        public int _RoomID { get; set; }
        [BindProperty]
        public Electricity Electricity { get; set; } = default!;
        public int _PaymentId { get; set; }
        public IActionResult OnGet(int? paymentDetailId)
        {
            var _paymentDetail = _context.PaymentDetails.SingleOrDefault(pd => pd.PaymentDetailId == paymentDetailId);
            _PaymentId = _paymentDetail.PaymentId;
            if (paymentDetailId == null)
            {
                return NotFound();
            }
            var query = _context.Electricities.Include(e => e.PaymentDetail).Include(e => e.Room);
            var electricityBill = (from e in query
                                   where e.PaymentDetailId == paymentDetailId
                                   select e).SingleOrDefault();
            if (electricityBill != null)
            {
                fromDate = (DateTime)electricityBill.FromDate;
                toDate = (DateTime)electricityBill.ToDate;
                var room = _context.Rooms.SingleOrDefault(r => r.RoomId == electricityBill.RoomId);
                RoomName = room.RoomName;
                _RoomID = room.RoomId;
                Electricity = electricityBill;
                return Page();
            }
            else
            {
                return NotFound();
            }
        }

        public  IActionResult OnPost()
        {
            _PaymentId = Convert.ToInt32(Request.Form["PaymentId"]);
            Electricity.PricePerNumber = 3000m;
            Electricity.Total = Electricity.PricePerNumber * Electricity.Quantity;
            _context.Entry(Electricity).State = EntityState.Modified;

            try
            {
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ElectricityExists(Electricity.ElectricityId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToPage("/Admin/PaymentDetail", new { paymentId = _PaymentId, roomID = Electricity.RoomId }); //paymentId = 3, roomID = 2
            //dang bị lỗi paymentID = 0;
        }
        private bool ElectricityExists(int id)
        {
            return (_context.Electricities?.Any(e => e.ElectricityId == id)).GetValueOrDefault();
        }
    }
}

Final_Project_PRN221/Pages/Admin/HomePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Final_Project_PRN221.Pages.Admin
{
    public class HomePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Final_Project_PRN221/Pages/Admin/Payment.cshtml.cs
using Final_Project_PRN221.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Final_Project_PRN221.Pages.Admin
{
    public class PaymentModel : PageModel
    {
        private readonly Project_PRN221Context _context;
        public PaymentModel(Project_PRN221Context context)
        {
            _context = context;
        }
        
        public DateTime fromDate = new DateTime();
        public DateTime toDate = new DateTime();
        [BindProperty]
        public PaymentDetail PaymentDetail { get; set; }

        [BindProperty]
        public int RoomID { get; set; }
        public bool checkAmount { get; set; }
        public async Task OnGetAsync()
        {
            var query = _context.Payments.Include(p => p.Room);
            var payments = (from p in query
                            where p.IsPaid == false
                            orderby p.Room.RoomName
                            select p).ToList();
            foreach (var p in payments)
            {
                if(!p.Amount.HasValue)
                {
                    checkAmount = true;
                    break;
                }
                else
                {
                    checkAmount= false;
                }
            }
            fromDate = (DateTime)payments[0].FromDate;
            toDate = (DateTime)payments[0].ToDate;
            ViewData["payments"] = payments;
        }

        public IActionResult OnPost()
        {
            var paymentDetailList = _context.PaymentDetails.SingleOrDefault(pd => pd.PaymentId == PaymentDetail.PaymentId);
            if (paymentDetailList == null)
            {
                PaymentDetail.RoomCharge = 8000000m;
                PaymentDetail.WaterMoney = 400000m;
                PaymentDetail.NetworkMoney = 400000m;
                PaymentDetail.CleanMoney = 120000m;
                PaymentDetail.DrinkWaterMoney = 80000m;

                _context.PaymentDetails.Add(PaymentDetail);
                _context.SaveChanges();
                return RedirectToPage("/Admin/PaymentDetail", new { paymentId = PaymentDetail.PaymentId , roomID = RoomID });
            }
            else
            {
                return RedirectToPage("/Admin/PaymentDetail", new { paymentId = PaymentDetail.PaymentId , roomID = RoomID }); //Check room xem lấy được không
            }
        }

        public async Task<IActionResult> OnPostSubmitData()
        {
            fromDate = DateTime.Parse(Request.Form["fromDate"]);
            toDate = DateTime.Parse(Request.Form["toDate"]);
            //1.Update isPaid của tất cả các trường thành true
            var paymentsToUpdate = _context.Payments.Where(p => p.IsPaid == false).Where(p => p.FromDate == fromDate && p.ToDate == toDate).ToList();
            if(paymentsToUpdate.Count > 0)
            {
                paymentsToUpdate.ForEach(p => p.IsPaid = true);
                await _context.SaveChangesAsync();
                foreach (var p in paymentsToUpdate)
                {
                    var newPayment = new Payment
                    {
                        RoomId = p.RoomId,
                        Amount = null,
                        FromDate = p.FromDate.Value.AddDays(120),
                        ToDate = p.ToDate.Value.AddDays(120),
                        IsPaid = false
                    };
                    _context.Payments.Add(newPayment);
                }
               await _context.SaveChangesAsync();
                return RedirectToPage();
            }
            else
            {
                return NotFound();
            }
            //2. Create dữ liệu mới (Tăng ngày fromDate, toDate, isPaid = false, Amount = null -> k cần set, RoomID dữ nguyên)          
        }
    }
}

Final_Project_PRN221/Pages/Admin/PaymentDetail.cshtml.cs
using Final_Project_PRN221.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Final_Project_PRN221.Pages.Admin
{
    public class PaymentDetailModel : PageModel
    {
        private readonly Project_PRN221Context _context;
        public PaymentDetailModel(Project_PRN221Context context)
        {
            _context = context;
        }

        [BindProperty]
        public int PaymentId { get; set; }
        [BindProperty]
        public int PaymentDetailId { get; set; }
        public string RoomName { get; set; }
        public int RoomID { get; set; }
        [BindProperty]
        public PaymentDetail PaymentDetail { get; set; } = default!;

        public decimal? TotalElectricAmount { get; set; }
        public IActionResult OnGet(int? paymentId, int? roomID)
        {
            if (paymentId == null || _context.PaymentDetails == null || roomID == null)
            {
                return NotFound();
            }
            var room = _context.Rooms.SingleOrDefault(r => r.RoomId == roomID);
            RoomName = room.RoomName;
            RoomID = room.RoomId;
            var paymentdetail = _context.PaymentDetails.Where(pd => pd.PaymentId == paymentId).SingleOrDefault();
            PaymentId = paymentdetail.PaymentId;
            PaymentDetailId = paymentdetail.PaymentDetailId;
            //Check electric total
            var query = _context.Electricities.Include(e => e.PaymentDetail);
            var electricResult = (from e in query
                                  where e.PaymentDetailId == paymentdetail.PaymentDetailId
                                  select e).SingleOrDefault();
            if (electricResult == null)
            {
                TotalElectricAmount = null;
            }
            else
            {
                TotalElectricAmount = electricResult.Total;
            }
            if (paymentdetail == null)
            {
                return NotFound();
            }
            else
            {
                PaymentDetail = paymentdetail;
            }
            return Page();
        }

        [BindProperty]
        public Electricity Electricity { get; set; } = default!;
        private decimal DiscountValue = 0;
        private bool checkExist = false;
        public IActionResult OnPost()
        {
            PaymentDetailId = Convert.ToInt32(Request.Form["_paymentDetailId"]);
            TotalElectricAmount = decimal.TryParse(Request.Form["TotalElectricAmount"].ToString(), out decimal result) ? result : 0;

            if (TotalElectricAmount == null || TotalElectricAmount == 0)
            {
                var query = _context.Payments.Include(p => p.PaymentDetails);
                var getDateFromPayment = (from fd in query
                                          where fd.PaymentId == PaymentId
                                          select fd).SingleOrDefault();
                //Check null
                var checkExitsList = _context.Electricities.ToList();
                foreach (var item in checkExitsList)
                {
                    if(item.PaymentDetailId == PaymentDetailId)
                    {
                        checkExist = true;
                        break;
                    }
                }
                if (checkExist)
                {
                    return RedirectToPage("/Admin/ElectricBill", new { paymentDetailId = Electricity.PaymentDetailId });
                }
                else
                {
                    Electricity.FromDate = getDateFromPayment.FromDate;
                    Electricity.ToDate = getDateFromPayment.ToDate;
                    Electricity.PricePerNumber = 3000m;

                    _context.Electricities.Add(Electricity);
                    _context.SaveChanges();
                    return RedirectToPage("/Admin/ElectricBill", new { paymentDetailId = Electricity.PaymentDetailId });
                }
            }
            else
            {               
                //if (!ModelState.IsValid)
                //{
                //    return Page();
                //}

                _context.Attach(PaymentDetail).State = EntityState.Modified;

                try
                {
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentDetailExists(PaymentDetail.PaymentDetailId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                var paymentUpdateAmount = _context.Payments.SingleOrDefault(p => p.PaymentId == PaymentDetail.PaymentId);
                if (paymentUpdateAmount != null)
                {
                    if(PaymentDetail.Discount == null)
                    {
                        DiscountValue = 0;
                    }
                    else
                    {
                        DiscountValue = (decimal)PaymentDetail.Discount;
                    }
                    paymentUpdateAmount.Amount = PaymentDetail.RoomCharge + PaymentDetail.WaterMoney + PaymentDetail.NetworkMoney + PaymentDetail.DrinkWaterMoney + PaymentDetail.CleanMoney + TotalElectricAmount - DiscountValue;
                    _context.Attach(paymentUpdateAmount).State = EntityState.Modified;
                    _context.SaveChanges();
                    return RedirectToPage("/Admin/Payment");
                }
                else
                {
                    return NotFound();
                }

            }
        }
        private bool PaymentDetailExists(int id)
        {
            return (_context.PaymentDetails?.Any(e => e.PaymentDetailId == id)).GetValueOrDefault();
        }
    }
}

Final_Project_PRN221/Pages/Admin/SetNotification.cshtml.cs
using Final_Project_PRN221.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Final_Project_PRN221.Pages.Admin
{
    public class SetNotificationModel : PageModel
    {
        private readonly Project_PRN221Context _context;
        public SetNotificationModel(Project_PRN221Context context)
        {
            _context = context;
        }
        [BindProperty]
        public Notification Notification { get; set; }
        public string Message { get; set; }
        public void OnGet(int? notificationID)
        {
            var noti = _context.Notifications.ToList();
            if(noti.Count() <= 0 )
            {
                Message = "There are no announcements yet";
            }
            else
            {
                if(notificationID != null)
                {
                    var notiDelete = (from n in noti
                                      where n.NotificationId== notificationID
                                      select n).SingleOrDefault();
                    _context.Notifications.Remove(notiDelete);
                    _context.SaveChanges();
                    noti.Remove(notiDelete);
                }
                ViewData["Notification"] = noti;
                Message = "Notification List";
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid || _context.Notifications == null || Notification == null)
            {
                return Page();
            }

            _context.Notifications.Add(Notification);
            await _context.SaveChangesAsync();

            return RedirectToPage();
        }
    }
}

Final_Project_PRN221/Pages/Admin/SignOut.cshtml.cs
using Final_Project_PRN221.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Final_Project_PRN221.Pages.Admin
{

    public class SignOutModel : PageModel
    {
        private readonly Project_PRN221Context _context;
        public SignOutModel(Project_PRN221Context context)
        {
            _context = context;
        }
        [BindProperty] public User user { get; set; } = default;

        public string Mess { get; set; } = default;

        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {

            var userCheck = _context.Users.SingleOrDefault(u => u.Username == user.Username);
            if (userCheck == null)
            {
                user.Role = 2;
                _context.Users.Add(user);
                _context.SaveChanges();
                Mess = "Tạo tài khoản thành công";
                return Page();
            }
            else
            {
                Mess = "Tài khoản đã tồn tại!";
                return Page();
            }
        }
    }
}

Final_Project_PRN221/Pages/Admin/ViewUserList.cshtml.cs
using Final_Project_PRN221.Models;
using Final_Project_PRN221.ServiceData;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Final_Project_PRN221.Pages.Admin
{
    public class ViewUserListModel : PageModel
    {
        private readonly Project_PRN221Context _context;
        private readonly DataService dataService;
        public ViewUserListModel(Project_PRN221Context context)
        {
            _context = context;
        }
        [BindProperty(SupportsGet = true)]
        public List<User> Users { get; set; } = default;
        public void OnGet(string? deleteUsername)
        {
            var query = _context.Users.Include(u => u.Room);
            var users = (from u in query
                         where u.Role == 2
                         orderby u.Room.RoomName
                         select u).ToList();
            if (deleteUsername != null)
            {
                var userDelete = (from u in users
                                  where u.Username == deleteUsername
                                  select u).SingleOrDefault();
                _context.Users.Remove(userDelete);
                _context.SaveChanges();
                users.Remove(userDelete);
            }

            ViewData["users"] = users;
        }
    }
}

Final_Project_PRN221/Pages/Users/HomePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Final_Project_PRN221.Pages.Users
{
    public class HomePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Final_Project_PRN221/Pages/Admin/ElectricBill.cshtml
@page
@model Final_Project_PRN221.Pages.Admin.ElectricBillModel
@{
    //Layout = null;
}
@*<h2>Hóa đơn điện phòng @Model.RoomName từ ngày @Model.fromDate.ToString("dd/MM/yyyy") đến ngày @Model.toDate.ToString("dd/MM/yyyy")</h2>
<form method="post">
    <input type="hidden" name="PaymentId" value="@Model._PaymentId" />
    <input type="hidden" asp-for="Electricity.ElectricityId"/>
    <input type="hidden" asp-for="Electricity.RoomId"/>
    <input type="hidden" asp-for="Electricity.FromDate"/>
    <input type="hidden" asp-for="Electricity.ToDate"/>
    <input type="hidden" asp-for="Electricity.PaymentDetailId"/>
    Tiền điện/Số
    <input asp-for="Electricity.PricePerNumber" id="price-per-number" disabled />
    <br />
    Số điện
    <input asp-for="Electricity.Quantity" id="quantity" onchange="calculateTotal()" />
    <br />
    Tiền điện phải đóng
    <input asp-for="Electricity.Total" id="total" disabled />
    <br />
    <input type="submit" class="btn btn-primary" value="Xác nhận" id="confirm-btn" disabled />
</form>*@

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Electric bill room @Model.RoomName from @Model.fromDate.ToString("dd/MM/yyyy") to @Model.toDate.ToString("dd/MM/yyyy")</h4>
            <p class="card-description"> You just need input quantity field </p>
            <form class="forms-sample" method="post">
                <input type="hidden" name="PaymentId" value="@Model._PaymentId" />
                <input type="hidden" asp-for="Electricity.ElectricityId" />
                <input type="hidden" asp-for="Electricity.RoomId" />
                <input type="hidden" asp-for="Electricity.FromDate" />
                <input type="hidden" asp-for="Electricity.ToDate" />
                <input type="hidden" asp-for="Electricity.PaymentDetailId" />
                <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Electric Money/ 1 Number</label>
                    <div class="col-sm-9">
                        <input asp-for="Electricity.PricePerNumber" style="color:red" id="price-per-number" disabled />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Quantity</label>
                    <div class="col-sm-9">
                        <input asp-for="Electricity.Quantity" id="quantity" onchange="calculateTotal()" />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputMobile" class="col-sm-3 col-form-label">Total</label>
                    <div class="col-sm-9">
                        <input style="color:red" asp-for="Electricity.Total" id="total" disabled />
                    </div>
                </div>
                <input type="submit" class="btn btn-primary" value="Xác nhận" id="confirm-btn" disabled />
            </form>
        </div>
    </div>
</div>

<script>
    function calculateTotal() {
        var pricePerNumber = parseFloat($("#price-per-number").val());
        var quantity = parseInt($("#quantity").val());
        var total = (pricePerNumber * quantity).toFixed(2);
        $("#total").val(total);
        if (total > 0) {
            $('#confirm-btn').prop('disabled', false);
        } else {
            $('#confirm-btn').prop('disabled', true);
        }
    }
</script>

Final_Project_PRN221/Pages/Admin/Payment.cshtml
@page
@using Final_Project_PRN221.Models;
@model Final_Project_PRN221.Pages.Admin.PaymentModel
@{
    var Payments = ViewData["payments"] as List<Payment>;
}

<h2>Room bill</h2>
@*NÚT CHUYỂN ĐỢT TIỀN PHÒNG*@
@*<form asp-page-handler="SubmitData" asp-page="/Admin/Payment">
    <input type="hidden" name="checkAmount" id="checkAmount" value="@Model.checkAmount" />
    <input type="hidden" name="fromDate" value="@Model.fromDate" />
    <input type="hidden" name="toDate" value="@Model.toDate" />
    <input type="submit" class="btn btn-primary" value="Sang đợt tiếp theo" id="confirm-btn" />
</form>

<p>Từ ngày @Model.fromDate.ToString("dd/MM/yyyy") đến ngày @Model.toDate.ToString("dd/MM/yyyy")</p>
<table class="table" style="border: 1px solid">
    <thead>
        <tr>
            <th>Phòng</th>
            <th>Tổng tiền phải đóng</th>
            <th>Xác nhận</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Payments)
        {
            <tr>
                <td>@p.Room.RoomName</td>
                @if (p.Amount == null)
                {
                    <td>Tổng số tiền phải xác nhận</td>
                }
                else
                {
                    <td>@p.Amount</td>
                }

                @if (p.IsPaid == true)
                {
                    <td>Đã đóng</td>
                }
                else
                {
                    <td>Chưa đóng</td>
                }
                <td>
                    <form method="post">
                        <input type="hidden" asp-for="RoomID" value="@p.Room.RoomId" />
                        <input type="hidden" asp-for="PaymentDetail.PaymentId" value="@p.PaymentId" />
                        <button type="submit" class="btn btn-primary">
                            Xem chi tiết hóa đơn
                        </button>
                    </form>
                </td>
                <td></td>
            </tr>
        }
    </tbody>
</table>*@
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form asp-page-handler="SubmitData" asp-page="/Admin/Payment">
                <input type="hidden" name="checkAmount" id="checkAmount" value="@Model.checkAmount" />
                <input type="hidden" name="fromDate" value="@Model.fromDate" />
                <input type="hidden" name="toDate" value="@Model.toDate" />
                <input type="submit" class="btn btn-primary" value="Sang đợt tiếp theo" id="confirm-btn" disabled/>
            </form>
            <h4 class="card-title">Bill from @Model.fromDate.ToString("dd/MM/yyyy") to @Model.toDate.ToString("dd/MM/yyyy")</h4>
            <p class="card-description">
                You must select the details button to adjust the necessary requirements
            </p>
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th> Room Name </th>
                            <th> Amount </th>
                            <th> Confirm </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var p in Payments)
                        {
                            <tr>
                                <td>@p.Room.RoomName</td>
                                @if (p.Amount == null)
                                {
                                    <td>Total amount need to confirm</td>
                                }
                                else
                                {
                                    <td>@p.Amount.Value.ToString("#,##0.00")</td>
                                }

                                @if (p.IsPaid == true)
                                {
                                    <td>Paid</td>
                                }
                                else
                                {
                                    <td>Not paid yet</td>
                                }
                                <td>
                                    <form method="post">
                                        <input type="hidden" asp-for="RoomID" value="@p.Room.RoomId" />
                                        <input type="hidden" asp-for="PaymentDetail.PaymentId" value="@p.PaymentId" />
                                        <button type="submit" class="btn btn-primary">
                                            Details
                                        </button>
                                    </form>
                                </td>
                                <td></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    const checkAmountInput = document.getElementById("checkAmount");
    if (checkAmountInput.value === "true") {
        $('#confirm-btn').prop('disabled', false);
    } else {
        $('#confirm-btn').prop('disabled', true);
    }
</script>

Final_Project_PRN221/Pages/Admin/SetNotification.cshtml
@page
@using Final_Project_PRN221.Models;
@model Final_Project_PRN221.Pages.Admin.SetNotificationModel
@{
    var noti = ViewData["Notification"] as List<Notification>;
}
@*<h2>Set notification</h2>
<form method="post">
    <label>Tạo thông báo</label><br />
    <textarea asp-for="Notification.Content"></textarea>
    <input type="submit" value="Gửi" class="btn btn-primary" />
</form>
@if (noti == null)
{
    <p>@Model.Message</p>
}
else
{
    <p>@Model.Message</p>
    @foreach (var n in noti)
    {
        <p>@n.Content</p>
        <hr />
    }
}*@
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Notification</h4>
            <p class="card-description"> Please typing to text area below to set notification for all users </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label for="exampleTextarea1">Set Notification</label>
                    <textarea class="form-control" asp-for="Notification.Content" id="exampleTextarea1" rows="4"></textarea>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
            </form>
            @if (noti == null)
            {
                <p class="card-description"> @Model.Message </p>
            }
            else
            {
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">@Model.Message</h4>
                        <div class="table-responsive">
                            <table class="table table-dark">
                                <thead>
                                    <tr>
                                        <th> Notification ID </th>
                                        <th> Content </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in noti)
                                    {
                                        <tr>
                                            <td>@item.NotificationId</td>
                                            <td>@item.Content</td>
                                            <td><a href="/Admin/SetNotification?notificationID=@item.NotificationId">Delete</a></td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Final_Project_PRN221/Pages/Admin/ViewUserList.cshtml
@page
@using Final_Project_PRN221.Models;
@model Final_Project_PRN221.Pages.Admin.ViewUserListModel
@{
    var users = ViewData["users"] as List<User>;
}
@*<h2>View user list</h2>
<table class="table">
    <thead>
        <tr>
            <th>Họ và tên</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Phòng</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in users)
        {
            <tr>
                <td>@item.Fullname</td>
                <td>@item.Email</td>
                <td>@item.Phone</td>
                <td>@item.Room.RoomName</td>
                <td><a href="./ViewUserList?deleteUsername=@item.Username">Xóa</a></td>
            </tr>
        }
    </tbody>
</table>*@
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">User list</h4>
            <div class="table-responsive">
                <table class="table table-dark">
                    <thead>
                        <tr>
                            <th> Full Name </th>
                            <th> Email </th>
                            <th> Phone Number </th>
                            <th> Room </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in users)
                        {
                            <tr>
                                <td>@item.Fullname</td>
                                <td>@item.Email</td>
                                <td>@item.Phone</td>
                                <td>@item.Room.RoomName</td>
                                <td><a href="./ViewUserList?deleteUsername=@item.Username">Delete</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>